language: python
# testing against multiple stable python3 versions
# most recent pytest does not support python 3.2
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install .[lint, test]
# command to run tests
script:
  - python scripts/test.py
  - python scripts/lint.py
notifications:
  slack:
    secure: SmyyDyvvloUgIxVdu//htvfx1VI1OKtxOGl1huwTDBXkhjNgY+KUObHThLpKF0N6J/e80qxfAyagJ3D2kZEmHCfGv8URpsYhzFeV1T2rp2WDnaTiGzhlbpvQLIHtGFyGzaRJzne8TJzrJrWS88JeEFwKJHbQM2SQWoJXxoa1pGoDKrtFUqe//cEtixGDPFp8rDEL/X3Xe/H6yNievzZi1FaKW90gNGIV3dfPl9Fyt2RX8Hh876rlyehBgs05mNh4SWgkNMzQln94HaKXzSUMwaSBZNKzF1oCwhgHNMGD4gy1eiToNumqhsktaIx/IVD/S0mZbormosSdrp+qfi1Pa/60Z/joQMLrEY3EqfcuB+QsB0ZABAJFsmNGoCQ0s4/7+XCxxGY1gSARguCIZ7RCGVsxT2nsa/oQJ1ES8NmFQ6TqFi+6/qS3VS+P+EAFAqhHgfK0u3qU5cg5agCtTDnANPjiJUUw7oFQRn+nQTVrt4/DrfVgO/0vzusYWTOuc3pPjBzcCp2YIRiGZiuxdilhDQ8I9G2lr0yFaftub+trFxyp0Wk9SMHotBJPwcrK1h9HE2n5PdOgcLaI6Da9geCA6y/nEhJ/BzEaQPSUaUIJna7qBuPKY9cZNBpIHak1S60W4joBC6GnS7aGAYIy61qwNMMp32pGoxJu4QHDRy8qIL4=
